name: Validate

on:
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run validation script
        run: bash ${GITHUB_WORKSPACE}/validate.sh
